### PR TITLE
Use inherits module instead of util

### PR DESCRIPTION
**Pull request by Kagami**
Hi. I replaced `util` module with `inherits` because it's much smaller (0.7K vs 15.6K) so it will be faster downloaded in a browser, etc.

### CODE REVIEW

**Comment by dcousens** [comment]
ACK, but its not unlikely that the `util` module is already being pulled in by browserify in other packages.   This might only be useful in the isolated case.  @dominictarr ?

**Comment by dominictarr** [comment]
@dcousens you are probably right, but I think @Kagami still has a pretty good case, until browserify can do dead code elimination, at least. Most uses of `util` is `util.inherits` i think, so probably you could update those other ones too.

**Comment by dominictarr** [comment]
@dcousens so I'm :+1: if you concur

**Comment by dominictarr** [comment]
okay I decided this isn't worth expending an email round trip. merging.

**Comment by dominictarr** [comment]
merged into 2.3.1

**Comment by Kagami** [comment]
Thanks!

**Comment by dcousens** [comment]
As I said, I'm OK with (and even for) this change.
But it is senseless without cooperation of other modules in which it is
most commonly combined, most of which [currently] use `util.inherits`.

**Comment by Kagami** [comment]
In my simple use case (~10 dependencies) libraries tend to use inherits: [[1]](https://github.com/indutny/hash.js/blob/master/lib/hash/utils.js#L2), [[2]](https://github.com/indutny/elliptic/blob/master/lib/elliptic/curve/mont.js#L5).
If some library uses `util.inherits` instead I think it's possible to cooperate with maintainer and fix this too (as @dominictarr said).

**Comment by dcousens** [comment]
Agreed.   I was just pointing this out :)

**Comment by dominictarr** [comment]
thanks

**Pull request merged**
